travis:
  secure:
    BINSTAR_TOKEN: kKIXcjb7iuEoX5K39rghqqckzDQ5rNuvnbdnsOyvSDfNwnGWSp0PCYAvDzwqWZ0YwecGQI4VqLPX24AzLsb7fnqc0/JQmzS0kjsLleLr3/Vy+5ZnOi3m0eXyHrOalFBHN7bzwkh52I67xygSDCuE+t9Sha76hKalHfoobx7mW4U6g7D0Eyehz3xSiy02RF1ZCXd6yVqx8U6sl7ZjcQMZdf1qU5Fuo/qhChkKF4CXsKpfSOdqfGF2BeyKi2fWR4buzo751H/xl62IDUMwe0KJ8eUmOLq/0yYueSoYP+jmKDKvudCxCN0JVBFSxqx8VXdEOqB52I9t3cJKHL/ylLkkyS843AZmh4IY/3Zf0WAnn4UiV+RJN/4zLYSIGXAjC0VSnQdZhoAnb8fmGbYFw7LCF+Fw5gq1YTMLrNKGAbVnj6uoWKSUTd8tR+QbaSstUzOfVFlWrnAhnQKL0n5b4VOwolcAbPJCW2y8dCis7g00fImpEc7D8EGPqbhonthcKofWiUuPtAi1MfLPMvT0E4tKViGeBMQ8P7KjX5VlabOCrz+y4XXXkuJKXSP3uLSEKFhMXxSSh8KaAQzjiptxPCY0QSpCHDjWYhljPB130q2uhlsJTE9W/4OJcvCV9y7McnQK2oF9nb2sK3Mm9AQs2ERqBAZxh4W0vmhq5Tn/YO3v6y8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
