travis:
  secure:
    BINSTAR_TOKEN: Re7o5JtR/Fds+JHBO2hsrACqq0ERzBlqaofS2tWXAP7uNdgvptewNpUleYLIWVqi3S9oN+51TQGukWWwVlm6lF1iaavYVS+vafrFLwzzAuFe1gm5qvCX/+leBDc5CAUBWOU79JjOdINsn7QKsP3MP7iMjyA+YyWTahRTPFKJwnYz5ti/EfVntEtelDkQYrau58AAAW+3t7jtNWPa3hzpfyyExb1LgLR2A5Yh9lhz9fCz/aPKJRIRhGm4ecu6J5y2g68LSVEECGGYzWeuMFqMAahIjwYJIFotqOXFkdV7MEJOfdrF0vryfYt1rc0lA9P3yFfO9V2oRJBbL0rUWIcn0F8OIwqX1Q35joIV+Up6W4Zp5tHS/yQtoZ1k3RLm/24ymjTWN9cxB/y64mNb6OjfQdH3F2cDyXKCn719Gj2WqNZuZMjY5gzJzzY/urzRZcqyisQCnr/1MLAGiNGafUaITkV1LIVCDAkfeKuVdZ2t2Tnp4oFYkjl+WIIfMMVKvueV8D0+QcnTRWgJSVoY/X4jeEY9KqU1c6risJ4422bq0Avs79tTwyks86vt/v2ffJQuDtQjLO0RmSPVa+0ix/3+cRQZJ8ce/VdUSD6c32LrOeTmeKC8RFyzG+L6kCaO9ylTGpNWgeK8eh+6hFz2D0i7m8OyY3MBmy8LThgkWo9tADg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
