travis:
  secure:
    BINSTAR_TOKEN: WcllwqZnezb6d271Joyqm5vpRXZFl5d3pdIF4E4V757zwvpYvXzJr6hLGTfi0FsxAPBhXhv/lUSKEgEmpnBpXr+wRsh9O524UDpNnMF8d0rFB5HsSWPGu/EYikuQGLLWS+diPR3VPm/B+TL14EzwQa1EqzT9P18NjyOP+WtLkYjHA3+MutALUaAg6i76gGKXADehx1yRrzhnyjBo54MI3jVWolCaJS/g+DzWBGUrAqcwR4K+kmWMgSYy3ZYpdP7XaPtoW3hMcnyujemjnh4sm/CHc5sqLFYa1XVav5jgnYoljzRvt3f2BmqNISwbk+7/hC25F8jvnE1zQlLhQSOXkpnp3jxnl1KshOZuY0Uy+L3gO5tEbPe2BCQo2hIRNEjM7PowHgihpaWmiElYgTZ0rCp1papFQ80B3FYyLf5SP92tq+r8sygq8Hbbg1hdhkQtns32g4aULT7vNZducaLnrCaSh0OunC6z2R1A22FBLpR3D7MS5+Pa3+ChrLKwqR0TIwBBZx/AECNaAQsaO/kEZ7xPMvVJJBZEEYOxPZ8w6+k1mD5kTUNnkUCyeQar1r0e6PS5DCuoaaHEdnDwJr6Mp5kX3F0jaVitq26jVbx+XIp4dTstOrHwDYIilapN5kuxM9veGR+i+4Pfh2kMHFNf13Q8J8NlZywuJ86pS/Z3Tfw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
